apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-tasky
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-tasky
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-tasky
  namespace: default
roleRef:
  kind: ClusterRole
  name: my-tasky
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: my-tasky
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-tasky
  name: my-tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tasky
  template:
    metadata:
      labels:
        app: my-tasky
    spec:
      containers:
      - image: famaten/my-public:my-tasky-v1.0
        name: my-tasky
        ports:
        - containerPort: 8080
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-tasky-secret
              key: secret_key
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: my-tasky-secret
              key: mongodb_uri
        - name: GIN_MODE
          valueFrom:
            secretKeyRef:
              name: my-tasky-secret
              key: gin_mode
        volumeMounts:
        - name: wizexercise
          mountPath: /data
      volumes:
      - name: wizexercise
        configMap:
          name: my-tasky-cm
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-tasky
  name: my-tasky-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: my-tasky
